# File: .github/workflows/1-Forest_1-DomainController_1-Workstation.yml

env:
  NamingConvention: "khl"
  ResourceGroup1Name: "1-Forest_1-DomainController_1-Workstation"
  PrdSubscription: "7d42fc1c-e7b8-49ec-85c4-403308e76d0b"
  StgSubscription: "19b978ca-c345-40ac-bf9f-7464f1148690"
  DevSubscription: "fa46a605-f32d-4d9e-8826-329809cf7a78"
  LabSubscription: "a87547df-4463-4b74-8832-9c978efe6667"
  VdiSubscription: "c0755cd6-5e30-4af8-8724-12b63a9a1686"
  Vnet1ID: "10.1"
  Location1:   "EastUS"

name: '1-Forest_1-DomainController_1-Workstation'
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  infrastructure:
    name: 'Deploy Infrastructure'
    runs-on: windows-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v2 

    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.GELVADE_PRD }}
        enable-AzPSSession: true

    - name: Create Resource Group
      uses: Azure/powershell@v1
      with:
        inlineScript:
          $RGCheck = Get-AzResourceGroup -Name "${{env.ResourceGroup1Name}}" -ErrorAction 0
          IF ($RGCheck -eq $Null) {New-AzResourceGroup -Name "${{env.ResourceGroup1Name}}" -Location "${{env.Location1}}"}
        azPSVersion: 3.1.0 

    - name: 'Deploy VNet'
      uses: azure/arm-deploy@v1
      with:
        deploymentname: 'DeployVNet1'
        subscriptionId: "${{env.PrdSubScription}}"
        resourceGroupName: "${{env.ResourceGroup1Name}}"
        template: 1-Forest_1-DomainController_1-Workstation/nestedtemplates/vnet.json   
        parameters:  
          vnetName="${{env.NamingConvention}}-VNet1"
          vnetprefix="${{env.Vnet1ID}}.0.0/16"
          subnet1Name="${{env.NamingConvention}}-VNet1-Subnet1"
          subnet1Prefix="${{env.Vnet1ID}}.1.0/24"
          subnet2Name="${{env.NamingConvention}}-VNet1-Subnet2"
          subnet2Prefix="${{env.Vnet1ID}}.2.0/24"  
          BastionsubnetPrefix="${{env.Vnet1ID}}.253.0/24"  
          location="${{env.Location1}}"

    - name: 'Deploy Bastion Host1'
      uses: azure/arm-deploy@v1
      with:
        deploymentname: 'DeployBastion1'
        subscriptionId: "${{env.PrdSubScription}}"
        resourceGroupName: "${{env.ResourceGroup1Name}}"
        template: 1-Forest_1-DomainController_1-Workstation/nestedtemplates/bastion.json   
        parameters:  
          publicIPAddressName="${{env.NamingConvention}}-VNet1-Bastion-pip"
          AllocationMethod="Static"
          vnetName="${{env.NamingConvention}}-VNet1"          
          subnetName="AzureBastion"
          location="${{env.Location1}}"                     